# Generated by Django 4.0.4 on 2022-04-18 12:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Authentication',
            fields=[
                ('loginid', models.CharField( max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('is_active', models.IntegerField(null=True)),
            ],
            managers=[
                ('loginauth_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
