# Generated by Django 4.0.4 on 2022-04-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_authentication',
            name='loginid',
            field=models.CharField(default='101', max_length=10, primary_key=True, serialize=False),
        ),
    ]
