# Generated by Django 4.0.4 on 2022-04-18 12:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0002_alter_tbl_authentication_loginid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tbl_authentication',
            managers=[
                ('loginauth_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
