# Generated by Django 4.0.4 on 2022-04-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0005_alter_tbl_authentication_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_authentication',
            name='role',
            field=models.IntegerField(default='1'),
        ),
    ]
