# Generated by Django 4.0.4 on 2022-04-19 10:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0006_tbl_authentication_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('username', models.CharField( max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=1)),
                ('Department', models.CharField(max_length=100)),
                ('Last_login_time', models.DateField()),
                ('Book1', models.TextField()),
                ('Book2', models.TextField()),
                ('Book3', models.TextField()),
            ],
            managers=[
                ('Studentdata_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
