# Generated by Django 4.0.4 on 2022-04-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0008_alter_student_data_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='Department',
            field=models.IntegerField(),
        ),
    ]
