# Generated by Django 4.0.4 on 2022-04-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0009_alter_student_data_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_data',
            old_name='Department',
            new_name='department',
        ),
    ]
