# Generated by Django 4.0.4 on 2022-04-21 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0010_rename_department_student_data_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_data',
            old_name='Book1',
            new_name='book1',
        ),
        migrations.RenameField(
            model_name='student_data',
            old_name='Book2',
            new_name='book2',
        ),
        migrations.RenameField(
            model_name='student_data',
            old_name='Book3',
            new_name='book3',
        ),
    ]
