# Generated by Django 4.0.4 on 2022-04-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0011_rename_book1_student_data_book1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='books_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_username', models.CharField(max_length=50)),
                ('book1', models.TextField()),
                ('book2', models.TextField()),
                ('book3', models.TextField()),
                ('book1_allocatedon', models.DateField()),
                ('book2_allocatedon', models.DateField()),
                ('book3_allocatedon', models.DateField()),
                ('book1_allocatedby', models.CharField(max_length=50)),
                ('book2_allocatedby', models.CharField(max_length=50)),
                ('book3_allocatedby', models.CharField(max_length=50)),
            ],
        ),
    ]
