# Generated by Django 4.0.4 on 2022-04-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0013_book_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='librarian_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_username', models.CharField(max_length=50, unique=True)),
                ('lib_name', models.CharField(max_length=50)),
                ('lib_age', models.IntegerField()),
                ('lib_gender', models.CharField(max_length=1)),
            ],
        ),
    ]
