# Generated by Django 4.0.4 on 2022-04-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0014_librarian_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian_data',
            name='lib_age',
            field=models.IntegerField(default='20'),
        ),
        migrations.AlterField(
            model_name='librarian_data',
            name='lib_name',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
