# Generated by Django 4.0.4 on 2022-04-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0015_alter_librarian_data_lib_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='books_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40, unique=True)),
                ('book_id', models.IntegerField()),
                ('book_author', models.CharField(max_length=30)),
                ('total_count', models.IntegerField(default='10')),
                ('description', models.CharField(max_length=200)),
                ('department', models.IntegerField()),
                ('location', models.IntegerField()),
            ],
        ),
    ]
