# Generated by Django 4.0.4 on 2022-04-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0016_books_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='books_data',
            name='book_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
