# Generated by Django 4.0.4 on 2022-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0017_remove_books_data_id_alter_books_data_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_data',
            name='book_id',
            field=models.IntegerField(default='1001', primary_key=True, serialize=False),
        ),
    ]
