# Generated by Django 4.0.4 on 2022-04-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0018_alter_books_data_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='book1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='book2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='book3',
            field=models.CharField(max_length=200),
        ),
    ]
