# Generated by Django 3.0.5 on 2022-05-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0024_tbl_authentication_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian_data',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student_data',
            name='Last_login_time',
        ),
        migrations.AlterField(
            model_name='book_history',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='books_history',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='librarian_data',
            name='lib_username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='department',
            field=models.IntegerField(null=True),
        ),
    ]
