# Generated by Django 3.0.5 on 2022-05-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0024_tbl_authentication_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_authentication',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
