# Generated by Django 3.0.5 on 2022-05-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0026_tbl_authentication_created_on'),
    ]

    operations = [
        
        
        migrations.AddField(
            model_name='books_data',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='books_data',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
                
    ]
