# Generated by Django 4.0.4 on 2022-05-25 11:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0028_auto_20220519_1238'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='book_history',
            name='book1_duedate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_history',
            name='book1_submiton',
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
       
    ]
